# Generated by Django 5.2 on 2025-04-24 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('design_type', models.CharField(choices=[('text', 'Custom Text'), ('image', 'Custom Image')], max_length=10)),
                ('custom_text', models.CharField(blank=True, max_length=100, null=True)),
                ('font_style', models.CharField(blank=True, choices=[('serif', 'Serif'), ('sans-serif', 'Sans-serif'), ('monospace', 'Monospace')], default='sans-serif', max_length=20, null=True)),
                ('custom_image', models.ImageField(blank=True, null=True, upload_to='custom_designs/')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=5)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=34.99, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
